### Embeds with FLAIR library

In [ ]:
!pip install flair -q

     |████████████████████████████████| 450kB 5.9MB/s 
     |████████████████████████████████| 19.7MB 1.3MB/s 
     |████████████████████████████████| 983kB 20.4MB/s 
     |████████████████████████████████| 798kB 53.7MB/s 
     |████████████████████████████████| 1.1MB 54.5MB/s 
     |████████████████████████████████| 71kB 10.8MB/s 
     |████████████████████████████████| 1.3MB 55.6MB/s 
     |████████████████████████████████| 2.9MB 58.7MB/s 
     |████████████████████████████████| 890kB 54.6MB/s 


In [ ]:


# init embedding
embedding = TransformerWordEmbeddings('bert-base-uncased')

# create a sentence
sentence = Sentence('The grass is green .')

# embed words in sentence
a=embedding.embed(sentence)

In [ ]:
from flair.embeddings import TransformerWordEmbeddings
from flair.data import Sentence

sentence = Sentence('क्या हाल है')

# use only last layers
embeddings = TransformerWordEmbeddings('xlm-roberta-large', layers='-1')
embeddings.embed(sentence)
print(sentence[0].embedding)


tensor([-0.0958, -0.1796, -0.0413,  ...,  0.1025,  0.4809,  0.0021],
       device='cuda:0')


In [ ]:
sentence[0]

Token: 1 क्या

In [ ]:
sentence =[ Sentence('क्या हाल है'), Sentence('क्या हाल है') ]

# use only last layers
embeddings = TransformerWordEmbeddings('xlm-roberta-large', layers='-1')
embeddings.embed(sentence)
print(sentence[0].embedding)

tensor([])


In [ ]:
sentence[0][0].embedding

tensor([-0.0958, -0.1796, -0.0413,  ...,  0.1025,  0.4809,  0.0021],
       device='cuda:0')

##ULMFit embeds

####Learn

In [ ]:
!pip install inltk -q
from inltk.inltk import setup
# setup('hi')
setup('en')

RuntimeError: ignored

Done!


In [ ]:
# !pip install torch==1.3.1+cpu -f https://download.pytorch.org/whl/torch_stable.html -q
!pip install torch==1.3.1+cpu -f https://download.pytorch.org/whl/torch_stable.html
# !pip install torch==1.3.1
#+cpu -f https://download.pytorch.org/whl/torch_stable.html -q


     |████████████████████████████████| 111.8MB 92kB/s 
ERROR: torchvision 0.8.1+cu101 has requirement torch==1.7.0, but you'll have torch 1.3.1+cpu which is incompatible.


In [ ]:
from inltk.inltk import get_embedding_vectors

In [ ]:
import warnings
import numpy as np
warnings.simplefilter("ignore")
from inltk.inltk import get_embedding_vectors

# get similar sentences to the one given in hindi
# output = get_embedding_vectors('मैं', 'hi')
output = get_embedding_vectors('how are you ?', 'en')

print(output)
# op = np.mean(output,axis=0)


In [ ]:
len(output[0])
len(op)

400

####Start

In [ ]:
import pandas as pd
import numpy as np
# train = pd.read_csv("/content/drive/My Drive/constraint2021/data/siva/farm_cleaned_t1_consthinditrain.tsv",sep='\t')
# train = train[['text', 'bin_label']]

# test = pd.read_csv("/content/drive/My Drive/constraint2021/data/siva/farm_cleaned_t1_consthindivalid.tsv",sep='\t')

test = pd.read_csv("/content/drive/My Drive/constraint2021/data/test_cleaned.csv")
test = test[['text']]

FileNotFoundError: ignored

In [ ]:
# trainembeds = np.zeros(shape=(len(train),400))
testembeds = np.zeros(shape=(len(test),400))

for i in range(len(test)):
  try:
    testembeds[i] = np.mean(get_embedding_vectors(test['text'][i],'hi'),axis=0)
  except Exception as e:
    print(e)
  if(i%100==0):
    print(i,'/',len(test))

In [ ]:
np.save('/content/drive/My Drive/constraint2021/data/siva/ulmfit_embeds_valid_t1_not_augmented.npy',testembeds)

##Basic Classification Classical Algos

In [ ]:
import sklearn
import numpy as np
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import classification_report,accuracy_score,confusion_matrix
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import train_test_split
from sklearn.model_selection import GridSearchCV, StratifiedKFold
from sklearn.svm import SVC
import pandas as pd

X =  np.load('/content/drive/My Drive/constraint2021/data/siva/muse_embeddings_train1.npy')
y =  pd.read_csv('/content/drive/My Drive/constraint2021/data/cleaned_consthinditrain.csv')['bin_label']
# X_train, X_val, y_train, y_val = train_test_split(X,y,test_size=0.2,stratify=y,random_state=42)
X_train, y_train = X,y
X_val =  np.load('/content/drive/My Drive/constraint2021/data/siva/muse_embeddings_val1.npy')
y_val =  pd.read_csv('/content/drive/My Drive/constraint2021/data/cleaned_consthindivalid.csv')['bin_label']
classifier = LogisticRegression() #MLPClassifier()#
model = simpleClassifier(X_train,X_val,y_train,y_val,test_size=0.2,is_stratified=True,classifier=classifier)
# mod = classifierwithGS(X_train,X_val,y_train,y_val,test_size=0.2,is_stratified=True,classifier=classifier)
# exhaustiveClassifierSearch(X_train,X_val,y_train,y_val,0.2,True)

----------Accuracy------------

0.7040690505548706
----------Confusion Matrix------------

[[229 147]
 [ 93 342]]
----------Classification Report------------

              precision    recall  f1-score   support

        host       0.71      0.61      0.66       376
         not       0.70      0.79      0.74       435

    accuracy                           0.70       811
   macro avg       0.71      0.70      0.70       811
weighted avg       0.70      0.70      0.70       811



In [ ]:
MUSE
----------Accuracy------------

0.7040690505548706
----------Confusion Matrix------------

[[229 147]
 [ 93 342]]
----------Classification Report------------

              precision    recall  f1-score   support

        host       0.71      0.61      0.66       376
         not       0.70      0.79      0.74       435

    accuracy                           0.70       811
   macro avg       0.71      0.70      0.70       811
weighted avg       0.70      0.70      0.70       811

In [ ]:
def simpleClassifier(X_train,X_val,y_train,y_val,test_size,is_stratified,classifier):
  # if(is_stratified):
  #   X_train, X_val, y_train, y_val = train_test_split(X,y,test_size=test_size,stratify=y,random_state=42)
  # else:
  #   X_train, X_val, y_train, y_val = train_test_split(X,y,test_size=test_size,random_state=42)
  if('max_iter' in classifier.get_params()):  #not all classifiers have maxiter param
    params = {"max_iter":4000}
    classifier.set_params(**params)
  try:
    classifier.fit(X_train,y_train)
    y_pred = classifier.predict(X_val)
    print("----------Accuracy------------\n")
    print(accuracy_score(y_true=y_val,y_pred=y_pred))
    print("----------Confusion Matrix------------\n")
    print(confusion_matrix(y_true=y_val,y_pred=y_pred))
    print("----------Classification Report------------\n")
    print(classification_report(y_true=y_val,y_pred=y_pred))
  except Exception as e:
    print(e)
  
  # return classifier

def gs(classifier,parameters,cv_fold,X_train,y_train):
  grid_search = GridSearchCV(classifier,param_grid=parameters,cv=StratifiedKFold(n_splits=cv_fold).split(X_train,y_train),verbose=2)
  model = grid_search.fit(X_train, y_train)
  print('Cross Validation Results:')
  print(model.cv_results_)
  return model

def classifierwithGS(X_train,X_val,y_train,y_val,test_size,is_stratified,classifier):
  # These params are valid only for logreg & similar type of classifiers 
  # parameters = [{"C":[1.0,10.0,20.0,40.0], "penalty":["l1","l2","elasticnet","none"],"solver":['liblinear','lbfgs','newton-cg', 'lbfgs', 'sag', 'saga'],"max_iter":[4000]}]
  parameters = {'solver': ['lbfgs','sgd','adam'], 'max_iter': [2000], 'alpha': 10.0 ** -np.arange(2, 6), 'hidden_layer_sizes':np.arange(10, 15), 'random_state':[0,1],'early_stopping':[True]}
  # 1000,1100,1200,1300,1400,1500,1600,1700,1800,1900,   10 for alpha ,2,3,4,5,6,7,8,9 for random_state
  cv_fold = 5
  # X_train, X_val, y_train, y_val = train_test_split(X,y,test_size=0.2,stratify=y,random_state=42)
  model = gs(classifier,parameters,cv_fold,X_train,y_train) 
  return model
  # bestparams = model.best_params_
  # print("Best params: ",bestparams)
  # logreg = LogisticRegression(C=bestparams["C"],max_iter=bestparams["max_iter"],solver=bestparams["solver"],penalty=bestparams["penalty"])
  # y_pred = logreg.predict(X_val)
  

  print("----------Accuracy------------\n")
  print(accuracy_score(y_true=y_val,y_pred=y_pred))
  print("----------Confusion Matrix------------\n")
  print(confusion_matrix(y_true=y_val,y_pred=y_pred))
  print("----------Classification Report------------\n")
  print(classification_report(y_true=y_val,y_pred=y_pred))

def exhaustiveClassifierSearch(X_train,X_val,y_train,y_val,test_size,is_stratified):
  import warnings
  warnings.filterwarnings("ignore")
  !pip install catboost
  !pip install lightgbm
  !pip install xgboost
  import sklearn
  from sklearn.neural_network import MLPClassifier
  from lightgbm import LGBMClassifier
  from catboost import CatBoostClassifier
  from xgboost.sklearn import XGBClassifier
  from sklearn.svm import LinearSVC
  from sklearn.tree import DecisionTreeClassifier,ExtraTreeClassifier
  from sklearn.ensemble import AdaBoostClassifier,GradientBoostingClassifier,ExtraTreesClassifier
  from sklearn.naive_bayes import MultinomialNB, BernoulliNB
  from sklearn.linear_model import RidgeClassifier,PassiveAggressiveClassifier,Perceptron,LogisticRegression
  from sklearn.metrics import confusion_matrix
  from sklearn.metrics import accuracy_score,classification_report

  classifiers = [MultinomialNB(), BernoulliNB(),DecisionTreeClassifier(),ExtraTreeClassifier(), XGBClassifier(),CatBoostClassifier(),ExtraTreesClassifier(),MLPClassifier(),LogisticRegression(),LinearSVC(),AdaBoostClassifier(),RidgeClassifier(),PassiveAggressiveClassifier(),Perceptron(),GradientBoostingClassifier(),LGBMClassifier()]
  
  for classifier in classifiers:
    print(str(classifier),'\n')
    simpleClassifier(X_train,X_val,y_train,y_val,test_size,is_stratified,classifier)
  



##Stacked Embeddings

In [ ]:
import pandas as pd
import numpy as np

df_t = pd.read_csv('/content/drive/MyDrive/constraint2021/data/cleaned_consthinditrain.csv')
df_val = pd.read_csv('/content/drive/MyDrive/constraint2021/data/cleaned_consthindivalid.csv')

In [ ]:
X_t=df_t['text']

In [ ]:
X_v=df_val['text']

In [ ]:
from flair.embeddings import FlairEmbeddings, TransformerWordEmbeddings
from flair.data import Sentence
xlmr_embedding = TransformerWordEmbeddings('xlm-roberta-large', layers='-1')
# init multilingual BERT
bert_embedding = TransformerWordEmbeddings('bert-base-multilingual-uncased',layers='-1')

In [ ]:
from flair.embeddings import StackedEmbeddings

# now create the StackedEmbedding object that combines all embeddings
stacked_embeddings = StackedEmbeddings(
    embeddings=[xlmr_embedding, bert_embedding])

In [ ]:
s[0].embedding.shape
#default (only passsingt he name, shape was 7168, else with l=-1, it is 1792) for stacked embedding  1024 for xlm-roberta & 768 for bert-multi-linual ARE THEY SIMPLY BEING CONCATENATED ? 

torch.Size([1792])

In [ ]:
import torch

In [ ]:
import pandas as pd
df_t = pd.read_csv('/content/drive/MyDrive/constraint2021/data/cleaned_consthinditrain.csv')
df_val = pd.read_csv('/content/drive/MyDrive/constraint2021/data/cleaned_consthindivalid.csv')
X_t=df_t['text']
X_v = df_val['text']


In [ ]:
def mean(sent,i):
  v_t=torch.zeros([1,1792],device='cuda:0')
  for j in range(len(sent)):
    v_t = v_t+sent[j].embedding
  v_t/=len(sent)
  if(i%100==0):
    print(i)
  return v_t
#started at 11.25 am ended at 11.30

In [ ]:
from flair.data import Sentence
# sents = [Sentence(X) for X in X_t]
print("HI")
sents = [Sentence(X) for X in X_v]
stacked_embeddings.embed(sents)
embeds = [mean(sents[i],i) for i in range(len(sents))]

HI
0
100
200
300
400
500
600
700
800


In [ ]:
embeds = [x.cpu().numpy() for x in embeds]
print(len(embeds))
embeds[0].shape

811


(1, 1792)

In [ ]:
embeds[0]


array([[-0.01056805, -0.07049138,  0.0980578 , ..., -0.09083792,
         0.06610274, -0.48191696]], dtype=float32)

In [ ]:
Y = [a[0] for a in X]
Z = [a[0] for a in X_val]
np.save('/content/drive/My Drive/constraint2021/data/siva/xlmr_large_bert_multi_stacked_embeddings_corrdim.npy',Y)
np.save('/content/drive/My Drive/constraint2021/data/siva/xlmr_large_bert_multi_stacked_embeddings_val_corrdim.npy',Z)

In [ ]:
# np.save('/content/drive/MyDrive/constraint2021/data/xlmr_large_bert_multi_stacked_embeddings.npy',embeds)
np.save('/content/drive/MyDrive/constraint2021/data/xlmr_large_bert_multi_stacked_embeddings_val.npy',embeds)

In [ ]:
# xlmr_embedding.embed(s)
# print(s[0].embedding.shape)

bert_embedding.embed(s)
print(s[0].embedding.shape)
# print(s[0],s[0].embedding)
print(len(s))


torch.Size([768])
22


##MUSE embeddings & FlairMultiEmbbedings

In [ ]:
!pip install flair -q

In [ ]:
# initialize embeddings
embeddings = MuseCrosslingualEmbeddings()

# two sentences in different languages
sentence_1 = Sentence("This red shoe is new .")
sentence_2 = Sentence("Dieser rote Schuh ist rot .")

# language code is auto-detected
print(sentence_1.get_language_code())
print(sentence_2.get_language_code())

# embed sentences
embeddings.embed([sentence_1, sentence_2])

In [ ]:
from flair.embeddings import MuseCrosslingualEmbeddings


In [ ]:
from flair.embeddings import FlairEmbeddings, TransformerWordEmbeddings,FlairMultiEmbbedings
from flair.data import Sentence
# embeddings = MuseCrosslingualEmbeddings()
embeddings = FlairMultiEmbbedings()
sentence_1 = Sentence("This red shoe is new .")
embeddings.embed(sentence_1)



ImportError: ignored

In [ ]:
import torch

In [ ]:
import pandas as pd
df_t = pd.read_csv('/content/drive/MyDrive/constraint2021/data/cleaned_consthinditrain.csv')
df_val = pd.read_csv('/content/drive/MyDrive/constraint2021/data/cleaned_consthindivalid.csv')
X_t=df_t['text']
X_v = df_val['text']


In [ ]:
def mean(sent,i):
  v_t=torch.zeros([1,300],device='cuda:0')
  for j in range(len(sent)):
    v_t = v_t+sent[j].embedding
  v_t/=len(sent)
  if(i%100==0):
    print(i)
  return v_t
#started at 11.25 am ended at 11.30

In [ ]:
from flair.data import Sentence
sents = [Sentence(X) for X in X_t]
print("HI")
# sents = [Sentence(X) for X in X_v]
# stacked_embeddings.embed(sents)
embeddings.embed(sents)
embeds = [mean(sents[i],i) for i in range(len(sents))]

HI
0
100
200
300
400
500
600
700
800
900
1000
1100
1200
1300
1400
1500
1600
1700
1800
1900
2000
2100
2200
2300
2400
2500
2600
2700
2800
2900
3000
3100
3200
3300
3400
3500
3600
3700
3800
3900
4000
4100
4200
4300
4400
4500
4600
4700
4800
4900
5000
5100
5200
5300
5400
5500
5600
5700


In [ ]:
import numpy as np

In [ ]:
embeds = [x.cpu().numpy() for x in embeds]
print(len(embeds))
embeds[0].shape

5728


(1, 300)

In [ ]:
np.save('/content/drive/MyDrive/constraint2021/data/muse_embeddings_train.npy',embeds)
# np.save('/content/drive/MyDrive/constraint2021/data/muse_embeddings_val.npy',embeds)

In [ ]:
Y = [a[0] for a in X]
Z = [a[0] for a in X_val]
np.save('/content/drive/My Drive/constraint2021/data/siva/muse_embeddings_train1.npy',Y)
np.save('/content/drive/My Drive/constraint2021/data/siva/muse_embeddings_val1.npy',Z)

In [ ]:
!pip install flair

In [ ]:
#linking drive
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
import pandas as pd
import numpy as np

df_t = pd.read_csv('/content/drive/My Drive/Projects/Hatespeech/Hindi/constraint2021/data/cleaned_consthinditrain.csv')
df_val = pd.read_csv('/content/drive/MyDrive/Projects/Hatespeech/Hindi/constraint2021/data/cleaned_consthindivalid.csv')

In [ ]:
X_t=df_t['text']

In [ ]:
X_v=df_val['text']

In [ ]:
from flair.embeddings import FlairEmbeddings, TransformerWordEmbeddings

# init Flair embeddings
flair_forward_embedding = FlairEmbeddings('multi-forward')
flair_backward_embedding = FlairEmbeddings('multi-backward')

# init multilingual BERT
bert_embedding = TransformerWordEmbeddings('bert-base-multilingual-cased')

In [ ]:
from flair.data import Sentence


In [ ]:
from flair.embeddings import StackedEmbeddings

# now create the StackedEmbedding object that combines all embeddings
stacked_embeddings = StackedEmbeddings(
    embeddings=[flair_forward_embedding, flair_backward_embedding, bert_embedding])

In [ ]:
s[0].embedding.shape
#default (only passsingt he name, shape was 7168, else with l=-1, it is 1792) for stacked embedding  1024 for xlm-roberta & 768 for bert-multi-linual ARE THEY SIMPLY BEING CONCATENATED ? 

NameError: ignored

In [ ]:
import torch

In [ ]:
import pandas as pd
df_t = pd.read_csv('/content/drive/MyDrive/constraint2021/data/cleaned_consthinditrain.csv')
df_val = pd.read_csv('/content/drive/MyDrive/constraint2021/data/cleaned_consthindivalid.csv')
X_t=df_t['text']
X_v = df_val['text']


In [ ]:
def mean(sent,i):
  v_t=torch.zeros([1,1792],device='cuda:0')
  for j in range(len(sent)):
    v_t = v_t+sent[j].embedding
  v_t/=len(sent)
  if(i%100==0):
    print(i)
  return v_t
#started at 11.25 am ended at 11.30

In [ ]:
from flair.data import Sentence
tsents = [Sentence(X) for X in X_t]
print("HI")
sents = [Sentence(X) for X in X_v]
stacked_embeddings.embed(sents)
embeds = [mean(sents[i],i) for i in range(len(sents))]

HI


In [ ]:
embeds = [x.cpu().numpy() for x in embeds]
print(len(embeds))
embeds[0].shape

811


(1, 1792)

In [ ]:
embeds[0]


array([[-0.01056805, -0.07049138,  0.0980578 , ..., -0.09083792,
         0.06610274, -0.48191696]], dtype=float32)

In [ ]:
Y = [a[0] for a in X]
Z = [a[0] for a in X_val]
np.save('/content/drive/My Drive/constraint2021/data/siva/xlmr_large_bert_multi_stacked_embeddings_corrdim.npy',Y)
np.save('/content/drive/My Drive/constraint2021/data/siva/xlmr_large_bert_multi_stacked_embeddings_val_corrdim.npy',Z)

In [ ]:
# np.save('/content/drive/MyDrive/constraint2021/data/xlmr_large_bert_multi_stacked_embeddings.npy',embeds)
np.save('/content/drive/MyDrive/constraint2021/data/xlmr_large_bert_multi_stacked_embeddings_val.npy',embeds)

In [ ]:
# xlmr_embedding.embed(s)
# print(s[0].embedding.shape)

bert_embedding.embed(s)
print(s[0].embedding.shape)
# print(s[0],s[0].embedding)
print(len(s))


torch.Size([768])
22


#Kannada HASOC DCM Embeds XLMR

In [ ]:
!pip install flair -q

     |████████████████████████████████| 1.3MB 6.6MB/s 
     |████████████████████████████████| 1.1MB 15.7MB/s 
     |████████████████████████████████| 2.9MB 30.5MB/s 
     |████████████████████████████████| 890kB 41.5MB/s 


In [ ]:
import pandas as pd
X_v = pd.read_csv('/content/drive/My Drive/HASOC2020/kannada_extra/data/kanglish_dev_stt.tsv',sep='\t')['text']
X_v

0                                            ದಿನಗಳು ಪಕ್ಕ
1      ಸೀರೆ ನೈವು ವೀಡಿಯೊ ಎನ್ / ಎ ಹುರಿದ ಮಾಡಿ ಅದ್ರೆ ಮದ್ವ...
2                                ಕೃಷಣಾ ಶಾಪ ತತ್ತೆಲೀಲಿಯೇಕು
3      ಕನ್ನಡ ಇವತ್ತು ರಾಷ್ಟ್ರೀಯ ಮತ್ತು ಅಂತಾರಾಷ್ಟ್ರೀಯ ಮಟ್...
4      ಕೇಳಿ ಕಾದಿರುವ ಭಾಂದವರೇನ್ಭುವಿಯಲ್ಲಿ ಅವನ ಅರಿತವರೆನ್ಯ...
                             ...                        
581    ಸುಪರ್ ಇಟ್ ಸಾಂಗ್ ಡಿ ಬಾಸ್ ಆಗಲೇ ಬೇಕಿತ್ತು ಸೂಪರ್ ರಕ...
582    ನಾನು ಕೂಡ ನಿರ್ದೇಶನ ಕೋರ್ಸ್ ಕಲಿತ ಇದ್ದೇನೆ ನಿಮ್ಮ ಈ ...
583                        ನಿನಿಗೆ ಬೇರ್ ಕೆಲ್ಸಾ ಇವ್ವ ಮದೋಕೆ
584    ದರ್ಶನ್ ಅಭಿಮಾನಿಗಳ ಕಡೆಯಿಂದ ಆಲ್ ದ ಬೆಸ್ಟ್ ಆಲ್ ದ ಬೆ...
585                                    ಕಥೆಯಲ್ಲಿ ದಮ್ ಇಲ್ಲ
Name: text, Length: 586, dtype: object

In [ ]:
def mean(sent,i):
  v_t=torch.zeros([1,1024],device='cuda:0')
  for j in range(len(sent)):
    v_t = v_t+sent[j].embedding
  v_t/=len(sent)
  if(i%100==0):
    print(i)
  return v_t
#started at 11.25 am ended at 11.30

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
from flair.data import Sentence
from flair.embeddings import TransformerWordEmbeddings

# sents = [Sentence(X) for X in X_t]
print("HI")
sents = [Sentence(X) for X in X_v]
embeddings = TransformerWordEmbeddings('xlm-roberta-large', layers='-1')
embeddings.embed(sents)
embeds = [mean(sents[i],i) for i in range(len(sents))]

In [ ]:
import torch
# embeds = [mean(sents[i],i) for i in range(len(sents))]


In [ ]:
embeds = [x.cpu().numpy() for x in embeds]
print(len(embeds))
embeds[0].shape

586


(1, 1024)

In [ ]:
embeds[0]
import numpy as np

In [ ]:
Y = [a[0] for a in embeds]
# Z = [a[0] for a in X_val]
np.save('/content/drive/My Drive/HASOC2020/kannada_extra/data/xlmr_large_embeddings_kannada_dev_stt.npy',Y)
# np.save('/content/drive/My Drive/constraint2021/data/siva/xlmr_large_bert_multi_stacked_embeddings_val_corrdim.npy',Z)

In [ ]:
# np.save('/content/drive/MyDrive/constraint2021/data/xlmr_large_bert_multi_stacked_embeddings.npy',embeds)
np.save('/content/drive/MyDrive/constraint2021/data/xlmr_large_bert_multi_stacked_embeddings_val.npy',embeds)

##Kannada classification

In [7]:
import sklearn
import numpy as np
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import classification_report,accuracy_score,confusion_matrix
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import train_test_split
from sklearn.model_selection import GridSearchCV, StratifiedKFold
from sklearn.svm import SVC
import pandas as pd

X =  np.load('/content/drive/My Drive/HASOC2020/kannada_extra/data/xlmr_large_embeddings_kannada_stt.npy')
y =  pd.read_csv('/content/drive/My Drive/HASOC2020/kannada_extra/data/kanglish_train_stt.tsv',sep='\t')['label']
# X_train, X_val, y_train, y_val = train_test_split(X,y,test_size=0.2,stratify=y,random_state=42)
X_train, y_train = X,y
X_val =  np.load('/content/drive/My Drive/HASOC2020/kannada_extra/data/xlmr_large_embeddings_kannada_dev_stt.npy')
y_val =  pd.read_csv('/content/drive/My Drive/HASOC2020/kannada_extra/data/kanglish_dev_stt.tsv',sep='\t')['label']
classifier = LogisticRegression() #MLPClassifier()#
model = simpleClassifier(X_train,X_val,y_train,y_val,test_size=0.2,is_stratified=True,classifier=classifier)
# mod = classifierwithGS(X_train,X_val,y_train,y_val,test_size=0.2,is_stratified=True,classifier=classifier)
# exhaustiveClassifierSearch(X_train,X_val,y_train,y_val,0.2,True)

----------Accuracy------------

0.8139931740614335
----------Confusion Matrix------------

[[397  29]
 [ 80  80]]
----------Classification Report------------

              precision    recall  f1-score   support

         NOT       0.83      0.93      0.88       426
         OFF       0.73      0.50      0.59       160

    accuracy                           0.81       586
   macro avg       0.78      0.72      0.74       586
weighted avg       0.81      0.81      0.80       586



In [1]:
def simpleClassifier(X_train,X_val,y_train,y_val,test_size,is_stratified,classifier):
  # if(is_stratified):
  #   X_train, X_val, y_train, y_val = train_test_split(X,y,test_size=test_size,stratify=y,random_state=42)
  # else:
  #   X_train, X_val, y_train, y_val = train_test_split(X,y,test_size=test_size,random_state=42)
  if('max_iter' in classifier.get_params()):  #not all classifiers have maxiter param
    params = {"max_iter":4000}
    classifier.set_params(**params)
  try:
    classifier.fit(X_train,y_train)
    y_pred = classifier.predict(X_val)
    print("----------Accuracy------------\n")
    print(accuracy_score(y_true=y_val,y_pred=y_pred))
    print("----------Confusion Matrix------------\n")
    print(confusion_matrix(y_true=y_val,y_pred=y_pred))
    print("----------Classification Report------------\n")
    print(classification_report(y_true=y_val,y_pred=y_pred))
  except Exception as e:
    print(e)
  
  # return classifier

##Kannada ensemble xlmr=b+xlmr-l

In [ ]:
# Install FARM previously:  !pip install farm==0.4.3 (lacks some updates compared tp 0.4.6)
# !pip install farm==0.4.6
# !pip install --upgrade farm
!pip install farm -q
!pip install pandas

In [3]:
# Here are the imports we need

# Here are the imports we need

import torch
from farm.modeling.tokenization import Tokenizer
from farm.data_handler.processor import TextClassificationProcessor
from farm.data_handler.data_silo import DataSilo
from farm.modeling.language_model import LanguageModel
from farm.modeling.prediction_head import TextClassificationHead
from farm.modeling.adaptive_model import AdaptiveModel
from farm.modeling.optimization import initialize_optimizer
from farm.train import Trainer,EarlyStopping
from farm.utils import MLFlowLogger

from farm.infer import Inferencer

01/06/2021 10:08:40 - INFO - farm.modeling.prediction_head -   Better speed can be achieved with apex installed from https://www.github.com/nvidia/apex .


In [4]:
import numpy as np
def get_res(inferenced_model,test_text):
  texts = []
  for sent in test_text:
    texts.append({'text':sent})
  result = inferenced_model.inference_from_dicts(dicts=texts) #return_json=True, ,multiprocessing_chunksize=5
  print("Done with results !! \n")
  pred_probs = np.zeros(shape=(len(texts),2))
  temp = np.zeros(shape=(1,2))
  i=0
  return result
def get_pred_probs(num_samples,inferenced_model,test):

  print(num_samples)
  texts = []
  # print( test[['text','label']][:num_samples])
  sample = test['text'][:num_samples]
  res = get_res(inferenced_model,sample)

  pred_probs = np.zeros(shape=(num_samples,2))
  temp = np.zeros(shape=(1,2))
  i=0
  for lis in res:    # in resurlt dict
    # print(lis)
    list_of_dicts = lis['predictions']
    # print(list_of_dicts)
    for dic in list_of_dicts:
      # print(dic)
      if(dic['label']=='NOT'):
        # print(dic['probability'])
        temp[0][0] = dic['probability']
        temp[0][1] = 1-dic['probability']
      else:
        temp[0][1] = dic['probability']
        temp[0][0] = 1-dic['probability']
      # break
      pred_probs[i] = temp
      i+=1
  return pred_probs
# print(pred_probs)
# res

In [ ]:
%%capture
import pandas as pd 
# saved_dir1 = "/content/drive/My Drive/HASOC2020/stuff/Data/final_saved_models/tanglish-final-xlmr-base-2e-5-50epochs_patience5"   #trained_model_path
saved_dir1 = '/content/drive/My Drive/HASOC2020/stuff/Data/extra_saved_models/kannada_stt_xlmr_base'
inferenced_model1 = Inferencer.load(saved_dir1,gpu=True,task_type='text_classification')   #,gpu=True,batch_size=4(by default :)))))))))))))))) MISSED THAT 

saved_dir2 = '/content/drive/My Drive/HASOC2020/stuff/Data/extra_saved_models/kannada_stt_mbert'
inferenced_model2 = Inferencer.load(saved_dir2,gpu=True,task_type='text_classification')


# WITH, gpu=True, inferencingis obviously fast

In [9]:

test = pd.read_csv('/content/drive/My Drive/HASOC2020/kannada_extra/data/kanglish_dev_stt.tsv',sep='\t')
# test = test.rename(columns={'Tweets_in_mal_script':'text'})
test

text  ...                            labels_old
0                                          ದಿನಗಳು ಪಕ್ಕ  ...                         Not_offensive
1    ಸೀರೆ ನೈವು ವೀಡಿಯೊ ಎನ್ / ಎ ಹುರಿದ ಮಾಡಿ ಅದ್ರೆ ಮದ್ವ...  ...                         Not_offensive
2                              ಕೃಷಣಾ ಶಾಪ ತತ್ತೆಲೀಲಿಯೇಕು  ...                         Not_offensive
3    ಕನ್ನಡ ಇವತ್ತು ರಾಷ್ಟ್ರೀಯ ಮತ್ತು ಅಂತಾರಾಷ್ಟ್ರೀಯ ಮಟ್...  ...                         Not_offensive
4    ಕೇಳಿ ಕಾದಿರುವ ಭಾಂದವರೇನ್ಭುವಿಯಲ್ಲಿ ಅವನ ಅರಿತವರೆನ್ಯ...  ...                         Not_offensive
..                                                 ...  ...                                   ...
581  ಸುಪರ್ ಇಟ್ ಸಾಂಗ್ ಡಿ ಬಾಸ್ ಆಗಲೇ ಬೇಕಿತ್ತು ಸೂಪರ್ ರಕ...  ...                         Not_offensive
582  ನಾನು ಕೂಡ ನಿರ್ದೇಶನ ಕೋರ್ಸ್ ಕಲಿತ ಇದ್ದೇನೆ ನಿಮ್ಮ ಈ ...  ...                         Not_offensive
583                      ನಿನಿಗೆ ಬೇರ್ ಕೆಲ್ಸಾ ಇವ್ವ ಮದೋಕೆ  ...  Offensive_Targeted_Insult_Individual
584  ದರ್ಶನ್ ಅಭಿಮಾನಿಗಳ ಕಡೆಯಿಂದ ಆಲ್ ದ ಬೆಸ್ಟ್ ಆಲ್ ದ ಬೆ...  ...                         Not_offensive
585                                  ಕಥೆಯಲ್ಲಿ ದಮ್ ಇಲ್ಲ  ...       Offensive_Targeted_Insult_Group

[586 rows x 3 columns]

In [10]:
from sklearn.metrics import classification_report
from collections import Counter

# test = pd.read_excel('/content/drive/My Drive/HASOC2020/Task-1/task1_dev.xlsx')
# test = pd.read_csv('/content/drive/My Drive/HASOC2020/Task-2/manglish_farm_test.csv')

pred_probs1 = get_pred_probs(len(test),inferenced_model1,test)
pred_probs2 = get_pred_probs(len(test),inferenced_model2,test)
pred_probs = pred_probs1 + pred_probs2
print(pred_probs)
# np.save('/content/drive/My Drive/HASOC2020/stuff/Data/znew_info/manglish_dev_xlmr-base_probs_rs0.npy',pred_probs)
predictedlabels = np.argmax(pred_probs,axis=1)
print(Counter(predictedlabels))
actualabels = test['label']
# print(classification_report(y_true = actualabels,y_pred = predictedlabels))
# print(predictedlabels)
# print(list(actualabels))

586


Inferencing Samples: 100%|██████████| 14/14 [00:00<00:00, 27.26 Batches/s]


Done with results !! 

586


Inferencing Samples: 100%|██████████| 14/14 [00:00<00:00, 27.40 Batches/s]

Done with results !! 

[[1.99921376e+00 7.86244869e-04]
 [1.73373818e+00 2.66261816e-01]
 [8.22325468e-01 1.17767453e+00]
 ...
 [9.98994708e-01 1.00100529e+00]
 [1.99932373e+00 6.76274300e-04]
 [1.99860346e+00 1.39653683e-03]]
Counter({0: 469, 1: 117})


In [11]:
lis = [ 'NOT' if(a==0) else 'OFF' for a in predictedlabels ]
print(classification_report(y_true = actualabels,y_pred = lis))


              precision    recall  f1-score   support

         NOT       0.85      0.93      0.89       426
         OFF       0.75      0.55      0.64       160

    accuracy                           0.83       586
   macro avg       0.80      0.74      0.76       586
weighted avg       0.82      0.83      0.82       586



In [ ]:
for i in range(len(pred_probs)):
  print(pred_probs[i][0]+pred_probs[i][1],sep='')